# Generated by Django 5.2.5 on 2025-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),

    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(
                to='services.Unit',
                on_delete=models.CASCADE,
                null=True,
                blank=True
            ),
        ),
    ]
