# Generated by Django 5.2.5 on 2025-08-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_fix_unit_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='services.unit', verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
