# Generated by Django 5.2.5 on 2025-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Показывать в счетчиках'),
        ),
    ]
