# Generated by Django 5.2.5 on 2025-08-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_is_show'),
        ('services', '0005_add_is_show_field'),
    ]

    operations = [
    ]
