# Generated by Django 5.2.5 on 2025-08-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_merge_20250813_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffservice',
            name='currency',
            field=models.CharField(default='грн', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='tariffservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariffservice',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.unit', verbose_name='Единица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.tariff'),
        ),
    ]
