# Generated by Django 5.2.5 on 2025-08-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_tariffservice_currency_tariffservice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffservice',
            name='currency',
        ),
    ]
