# Generated by Django 5.2.5 on 2025-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_tariffservice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffservice',
            name='currency',
            field=models.CharField(default='грн', editable=False, max_length=10, verbose_name='Валюта'),
        ),
    ]
