# Generated by Django 5.2.5 on 2025-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_tariffservice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='currency',
            field=models.CharField(default='грн', max_length=10, verbose_name='Валюта'),
        ),
    ]
