# Generated by Django 5.2.5 on 2025-08-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_tariffservice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='currency',
        ),
    ]
