# Generated by Django 5.2.5 on 2025-08-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_paimentdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaimentDetail',
            new_name='PaymentDetail',
        ),
    ]
