# Generated by Django 5.2.5 on 2025-08-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to='slides/')),
                ('slide2', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('slide3', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blocks/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.main')),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.seo'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('map', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.seo')),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.seo'),
        ),
        migrations.CreateModel(
            name='ServiceStr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tariff', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.seo')),
            ],
        ),
    ]
