# Generated by Django 5.2.5 on 2025-09-12 10:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
