# Generated by Django 5.2.5 on 2025-09-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_alter_main_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='web_site.main'),
        ),
    ]
