# Generated by Django 5.2.5 on 2025-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_block_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
