# Generated by Django 5.2.5 on 2025-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(choices=[('main', 'Основная'), ('additional', 'Дополнительная')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
