# Generated by Django 5.2.5 on 2025-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, upload_to='blocks/'),
        ),
    ]
