# Generated by Django 5.2.5 on 2025-09-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_alter_block_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='web_site.aboutus'),
        ),
    ]
