# Generated by Django 5.2.5 on 2025-09-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_alter_gallery_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web_site.aboutus'),
        ),
    ]
