services:
  web:
    build: .
    command: [ "poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000" ]

    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A settings worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
      - web
    networks:
      - app-network

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
      - ./static_collected:/app/static_collected:ro
