# Generated by Django 5.2.5 on 2025-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('area', models.FloatField(verbose_name='Площадь, м²')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.TextField(verbose_name='Address')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 5')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название секции')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
