# Generated by Django 5.2.5 on 2025-08-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_remove_house_user_staff'),
        ('users', '0006_user_date_birthday_user_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_Role', to='users.role'),
        ),
    ]
