# Generated by Django 5.2.5 on 2025-08-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
