# Generated by Django 5.2.5 on 2025-08-13 12:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('building', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Роль')),
                ('has_statistic', models.BooleanField(default=False, verbose_name='Статистика')),
                ('has_cashbox', models.BooleanField(default=False, verbose_name='Касса')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='Квитанции')),
                ('has_personal_account', models.BooleanField(default=False, verbose_name='личный счёт')),
                ('has_user', models.BooleanField(default=False, verbose_name='Работники')),
                ('has_owner', models.BooleanField(default=False, verbose_name='Владельци')),
                ('has_message', models.BooleanField(default=False, verbose_name='Сообщения')),
                ('has_applications', models.BooleanField(default=False, verbose_name='')),
                ('has_managment', models.BooleanField(default=False, verbose_name='Управление')),
                ('has_service', models.BooleanField(default=False, verbose_name='Услуги')),
                ('has_role', models.BooleanField(default=False, verbose_name='Роли')),
                ('has_tariff', models.BooleanField(default=False, verbose_name='Тарифы')),
                ('has_payment_details', models.BooleanField(default=False, verbose_name='Платежные даные')),
                ('has_counter', models.BooleanField(default=False, verbose_name='Счётчики')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='Аватар')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('viber', models.CharField(blank=True, max_length=255, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('work', 'In Progress'), ('done', 'Done')], default='new', max_length=4, verbose_name='Статус заявки')),
                ('summary', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.house', verbose_name='Дом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
