# Generated by Django 5.2.5 on 2025-08-12 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='viber',
            field=models.CharField(blank=True, default=11, max_length=255, verbose_name='Viber'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Роль')),
                ('has_statistic', models.BooleanField(default=False, verbose_name='Статистика')),
                ('has_cashbox', models.BooleanField(default=False, verbose_name='Касса')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='Квитанции')),
                ('has_personal_account', models.BooleanField(default=False, verbose_name='личный счёт')),
                ('has_user', models.BooleanField(default=False, verbose_name='Работники')),
                ('has_owner', models.BooleanField(default=False, verbose_name='Владельци')),
                ('has_message', models.BooleanField(default=False, verbose_name='Сообщения')),
                ('has_applications', models.BooleanField(default=False, verbose_name='')),
                ('has_managment', models.BooleanField(default=False, verbose_name='Управление')),
                ('has_service', models.BooleanField(default=False, verbose_name='Услуги')),
                ('has_role', models.BooleanField(default=False, verbose_name='Роли')),
                ('has_tariff', models.BooleanField(default=False, verbose_name='Тарифы')),
                ('has_payment_details', models.BooleanField(default=False, verbose_name='Платежные даные')),
                ('has_counter', models.BooleanField(default=False, verbose_name='Счётчики')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('work', 'In Progress'), ('done', 'Done')], default='new', max_length=4, verbose_name='Статус заявки')),
                ('summary', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.house', verbose_name='Дом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
