# Generated by Django 5.2.5 on 2025-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('work', 'In Progress'), ('done', 'Done')], default='new', max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
