# Generated by Django 5.2.5 on 2025-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('work', 'Активный'), ('done', 'Отключен')], default='new', max_length=4, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('work', 'Активный'), ('done', 'Отключен')], default='new', max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
