# Generated by Django 5.2.5 on 2025-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=' ', max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
