# Generated by Django 5.2.5 on 2025-10-24 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_box_number', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_conducted', models.BooleanField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted', models.BooleanField()),
                ('status', models.CharField(choices=[('new', 'Оплачено'), ('zero', 'Не оплачено'), ('counted', 'Частично оплачено')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('mount', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('out', 'Расход'), ('in', 'Приход')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Лицевой счет')),
                ('status', models.CharField(choices=[('activ', 'Активный'), ('desactiv', 'Неактивный')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='templates/')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
