# Generated by Django 5.2.5 on 2025-08-12 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('new', 'Расход'), ('zero', 'Приход')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted', models.BooleanField()),
                ('status', models.CharField(choices=[('new', 'Оплачено'), ('zero', 'Неоплачено'), ('counted', 'Частично оплачено')], max_length=20)),
                ('account_number', models.UUIDField()),
                ('mount', models.DateField()),
                ('date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.counter')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.UUIDField()),
                ('status', models.BooleanField(default=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_box_number', models.UUIDField()),
                ('date', models.DateField()),
                ('is_conducted', models.BooleanField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_cashboxes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cashboxes', to=settings.AUTH_USER_MODEL)),
                ('payment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.paymentitem')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.personalaccount')),
            ],
        ),
    ]
