# Generated by Django 5.2.5 on 2025-10-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tariff'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financials.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tariff_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_service', to='services.tariffservice'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='payment_articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.paymentarticles'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.personalaccount'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.personalaccount'),
        ),
    ]
