# Generated by Django 5.2.5 on 2025-08-13 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_initial'),
        ('financials', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tariff'),
        ),
        migrations.AddField(
            model_name='invoiseitem',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.counter'),
        ),
        migrations.AddField(
            model_name='invoiseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.invoice'),
        ),
        migrations.AddField(
            model_name='invoiseitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='payment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.paymentitem'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.apartment'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.personalaccount'),
        ),
    ]
