# Generated by Django 5.2.5 on 2025-08-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentItem',
            new_name='PaymentArticles',
        ),
        migrations.RenameField(
            model_name='cashbox',
            old_name='payment_item',
            new_name='payment_articles',
        ),
    ]
