# Generated by Django 5.2.5 on 2025-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_rename_paymentitem_paymentarticles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentarticles',
            name='record_type',
            field=models.CharField(choices=[('expenses', 'Расход'), ('coming', 'Приход')], max_length=20),
        ),
    ]
