# Generated by Django 5.2.5 on 2025-11-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_add_personal_account_to_invoice'),
        ('financials', '0004_add_is_default_to_template'),
    ]

    operations = [
    ]
