# Generated by Django 5.2.5 on 2025-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_paymentarticles_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentarticles',
            name='record_type',
            field=models.CharField(choices=[('out', 'Расход'), ('in', 'Приход')], max_length=20),
        ),
    ]
