"""Initialize the database with default data, including the superuser account."""

import os

SUPERUSER_USERNAME = os.getenv("DJANGO_SUPERUSER_USERNAME", "superuser")
SUPERUSER_EMAIL = os.getenv("DJANGO_SUPERUSER_EMAIL", "admin@example.com")
SUPERUSER_PASSWORD = os.getenv("DJANGO_SUPERUSER_PASSWORD")

ROLES = [
    {
        "name": "Директор",
        "is_worker_role": True,
        "has_statistic": True,
        "has_cashbox": True,
        "has_house": True,
        "has_invoice": True,
        "has_personal_account": True,
        "has_apartment": True,
        "has_user": True,
        "has_owner": True,
        "has_message": True,
        "has_applications": True,
        "has_managment": True,
        "has_service": True,
        "has_role": True,
        "has_tariff": True,
        "has_payment_details": True,
        "has_counter": True,
    },
    {
        "name": "Бухгалтер",
        "is_worker_role": True,
        "has_statistic": True,
        "has_cashbox": True,
        "has_house": True,
        "has_invoice": True,
        "has_personal_account": True,
        "has_apartment": True,
        "has_user": True,
        "has_owner": True,
        "has_message": True,
        "has_applications": True,
        "has_managment": True,
        "has_service": True,
        "has_role": True,
        "has_tariff": True,
        "has_payment_details": True,
        "has_counter": True,
    },
    {
        "name": "Управляющий",
        "is_worker_role": True,
        "has_statistic": True,
        "has_cashbox": True,
        "has_house": True,
        "has_invoice": True,
        "has_personal_account": True,
        "has_apartment": True,
        "has_user": True,
        "has_owner": True,
        "has_message": True,
        "has_applications": True,
        "has_managment": True,
        "has_service": True,
        "has_role": True,
        "has_tariff": True,
        "has_payment_details": True,
        "has_counter": True,
    },
    {
        "name": "Электрик",
        "is_worker_role": True,
        "has_statistic": False,
        "has_cashbox": False,
        "has_house": False,
        "has_invoice": False,
        "has_personal_account": False,
        "has_apartment": False,
        "has_user": False,
        "has_owner": False,
        "has_message": True,
        "has_applications": True,
        "has_managment": False,
        "has_service": False,
        "has_role": False,
        "has_tariff": False,
        "has_payment_details": False,
        "has_counter": False,
    },
    {
        "name": "Сантехник",
        "is_worker_role": True,
        "has_statistic": False,
        "has_cashbox": False,
        "has_house": False,
        "has_invoice": False,
        "has_personal_account": False,
        "has_apartment": False,
        "has_user": False,
        "has_owner": False,
        "has_message": True,
        "has_applications": True,
        "has_managment": False,
        "has_service": False,
        "has_role": False,
        "has_tariff": False,
        "has_payment_details": False,
        "has_counter": False,
    },
]


STAFF = [
    {
        "first_name": "Иван",
        "second_name": "Иванович",
        "last_name": "Иванов",
        "email": "ivanov@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 1,
        "description": "Менеджер",
        "status": "active",
        "is_staff": True,
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Директор",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Скрудж",
        "second_name": "Иванович",
        "last_name": "Иванов",
        "email": "ivanov2@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 2,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Бухгалтер",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Николай",
        "second_name": "Андреевич",
        "last_name": "Скворцов",
        "email": "ivanov3@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 3,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Управляющий",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Леонид",
        "second_name": "Сергеевич",
        "last_name": "Дроздов",
        "email": "ivanov4@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 4,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Электрик",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Валерий",
        "second_name": "Павлович",
        "last_name": "Швец",
        "email": "ivanov5@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 5,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Сантехник",
        "password": "supersecurepassword",
    },
    # ToDo Second grup
    {
        "first_name": "Егор",
        "second_name": "Иванович",
        "last_name": "Поддубный",
        "email": "ivanov6@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 6,
        "description": "Менеджер",
        "status": "active",
        "is_staff": True,
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Директор",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Игорь",
        "second_name": "Дмитриевич",
        "last_name": "Курчатов",
        "email": "ivanov7@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 7,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Бухгалтер",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Николай",
        "second_name": "Андреевич",
        "last_name": "Сидоров",
        "email": "ivanov8@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 8,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Управляющий",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Леонид",
        "second_name": "Сергеевич",
        "last_name": "Шпак",
        "email": "ivanov9@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 9,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Электрик",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Валерий",
        "second_name": "Павлович",
        "last_name": "Крутопалов",
        "email": "ivanov10@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 10,
        "is_staff": True,
        "description": "Менеджер",
        "status": "active",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "role_id": "Сантехник",
        "password": "supersecurepassword",
    },
]


PAYMENT_ARTICLES = [
    {"name": "Озеленение", "record_type": "out"},
    {"name": "Вывоз мусора", "record_type": "out"},
    {"name": "Коммунальный платёж", "record_type": "in"},
    {"name": "Прочее", "record_type": "in"},
]

PAYMENT_DETAIL = [
    {"name": "Тихая Пристань", "description": "UA173000010000032003102901026"},
]

UNITS = [
    {"name": "кВт/час"},
    {"name": "м³"},
    {"name": "час"},
    {"name": "место"},
]

SERVICES = [
    {
        "name": "Холодная Вода",
        "unit_name": "м³",
    },
    {
        "name": "Горячая  Вода",
        "unit_name": "м³",
    },
    {
        "name": "Парковка",
        "unit_name": "место",
    },
    {
        "name": "Электричество ",
        "unit_name": "кВт/час",
    },
]


TARIFFS = [
    {"title": "Тариф ЖКХ 2025", "description": "Базовый тариф на услуги ЖКХ"},
    {
        "title": "Тариф Комфорт 2025",
        "description": "Повышенный тариф с включёнными услугами",
    },
]

TARIFF_SERVICES = [
    {
        "tariff_title": "Тариф ЖКХ 2025",
        "service_name": "Холодная Вода",
        "price": 50,
        "currency": "грн",
    },
    {
        "tariff_title": "Тариф ЖКХ 2025",
        "service_name": "Горячая  Вода",
        "price": 70,
        "currency": "грн",
    },
    {
        "tariff_title": "Тариф ЖКХ 2025",
        "service_name": "Электричество",
        "price": 120,
        "currency": "грн",
    },
    {
        "tariff_title": "Тариф Комфорт 2025",
        "service_name": "Горячая  Вода",
        "price": 70,
        "currency": "грн",
    },
    {
        "tariff_title": "Тариф Комфорт 2025",
        "service_name": "Холодная Вода ",
        "price": 50,
        "currency": "грн",
    },
    {
        "tariff_title": "Тариф Комфорт 2025",
        "service_name": "Электричество",
        "price": 150,
        "currency": "грн",
    },
]

OWNERS = [
    {
        "first_name": "Иван",
        "second_name": "Иванович",
        "last_name": "Иванов",
        "email": "ivanov@example.com",
        "date_birthday": "1990-01-01",
        "image": None,
        "user_id": 31,
        "description": "Менеджер",
        "status": "work",
        "phone": "+380123456789",
        "viber": "+380123456789",
        "telegram": "@ivanov",
        "password": "supersecurepassword",
    },
    {
        "first_name": "Елена",
        "second_name": "Сергеевна",
        "last_name": "Смирнова",
        "email": "smirnova@example.com",
        "date_birthday": "1985-05-15",
        "image": None,
        "user_id": 32,
        "description": "Главный бухгалтер",
        "status": "work",
        "phone": "+380987654321",
        "viber": "+380987654321",
        "telegram": "@smirnova_e",
        "password": "securepass2",
    },
    {
        "first_name": "Александр",
        "second_name": "Николаевич",
        "last_name": "Петров",
        "email": "petrov@example.com",
        "date_birthday": "1992-11-20",
        "image": None,
        "user_id": 33,
        "description": "Ведущий программист",
        "status": "work",
        "phone": "+380501112233",
        "viber": "+380501112233",
        "telegram": "@alex_p",
        "password": "securepass3",
    },
    {
        "first_name": "Ольга",
        "second_name": "Владимировна",
        "last_name": "Волкова",
        "email": "volkova@example.com",
        "date_birthday": "1988-03-10",
        "image": None,
        "user_id": 34,
        "description": "Специалист по подбору персонала",
        "status": "work",
        "phone": "+380674445566",
        "viber": "+380674445566",
        "telegram": "@olga_hr",
        "password": "securepass4",
    },
    {
        "first_name": "Дмитрий",
        "second_name": "Алексеевич",
        "last_name": "Козлов",
        "email": "kozlov@example.com",
        "date_birthday": "1983-07-25",
        "image": None,
        "user_id": 35,
        "description": "Руководитель отдела продаж",
        "status": "work",
        "phone": "+380667778899",
        "viber": "+380667778899",
        "telegram": "@dima_sale",
        "password": "securepass5",
    },
    {
        "first_name": "Мария",
        "second_name": "Ивановна",
        "last_name": "Новикова",
        "email": "novikova@example.com",
        "date_birthday": "1995-09-02",
        "image": None,
        "user_id": 36,
        "description": "Маркетолог",
        "status": "work",
        "phone": "+380931002030",
        "viber": "+380931002030",
        "telegram": "@maria_m",
        "password": "securepass6",
    },
    {
        "first_name": "Сергей",
        "second_name": "Дмитриевич",
        "last_name": "Морозов",
        "email": "morozov@example.com",
        "date_birthday": "1978-12-08",
        "image": None,
        "user_id": 37,
        "description": "Инженер-конструктор",
        "status": "work",
        "phone": "+380685006070",
        "viber": "+380685006070",
        "telegram": "@serg_eng",
        "password": "securepass7",
    },
    {
        "first_name": "Анна",
        "second_name": "Геннадьевна",
        "last_name": "Павлова",
        "email": "pavlova@example.com",
        "date_birthday": "1991-04-14",
        "image": None,
        "user_id": 38,
        "description": "Юрист",
        "status": "work",
        "phone": "+380998009001",
        "viber": "+380998009001",
        "telegram": "@anna_law",
        "password": "securepass8",
    },
    {
        "first_name": "Николай",
        "second_name": "Игоревич",
        "last_name": "Федоров",
        "email": "fedorov@example.com",
        "date_birthday": "1980-06-30",
        "image": None,
        "user_id": 39,
        "description": "Системный администратор",
        "status": "work",
        "phone": "+380632223344",
        "viber": "+380632223344",
        "telegram": "@kolya_sys",
        "password": "securepass9",
    },
    {
        "first_name": "Татьяна",
        "second_name": "Олеговна",
        "last_name": "Михайлова",
        "email": "mikhailova@example.com",
        "date_birthday": "1987-10-05",
        "image": None,
        "user_id": 40,
        "description": "Секретарь",
        "status": "work",
        "phone": "+380975556677",
        "viber": "+380975556677",
        "telegram": "@tanya_sec",
        "password": "securepass10",
    },
    {
        "first_name": "Андрей",
        "second_name": "Викторович",
        "last_name": "Попов",
        "email": "popov@example.com",
        "date_birthday": "1994-02-18",
        "image": None,
        "user_id": 41,
        "description": "Аналитик данных",
        "status": "work",
        "phone": "+380509990011",
        "viber": "+380509990011",
        "telegram": "@andrey_data",
        "password": "securepass11",
    },
    {
        "first_name": "Виктория",
        "second_name": "Евгеньевна",
        "last_name": "Васильева",
        "email": "vasilyeva@example.com",
        "date_birthday": "1989-08-28",
        "image": None,
        "user_id": 42,
        "description": "Менеджер по закупкам",
        "status": "work",
        "phone": "+380671234567",
        "viber": "+380671234567",
        "telegram": "@vica_buy",
        "password": "securepass12",
    },
    {
        "first_name": "Михаил",
        "second_name": "Георгиевич",
        "last_name": "Кузнецов",
        "email": "kuznetsov@example.com",
        "date_birthday": "1975-01-20",
        "image": None,
        "user_id": 43,
        "description": "Главный инженер",
        "status": "work",
        "phone": "+380662345678",
        "viber": "+380662345678",
        "telegram": "@misha_chief",
        "password": "securepass13",
    },
    {
        "first_name": "Екатерина",
        "second_name": "Александровна",
        "last_name": "Соколова",
        "email": "sokolova@example.com",
        "date_birthday": "1993-03-03",
        "image": None,
        "user_id": 44,
        "description": "Копирайтер",
        "status": "work",
        "phone": "+380933456789",
        "viber": "+380933456789",
        "telegram": "@katya_copy",
        "password": "securepass14",
    },
    {
        "first_name": "Артем",
        "second_name": "Павлович",
        "last_name": "Лебедев",
        "email": "lebedev@example.com",
        "date_birthday": "1986-07-11",
        "image": None,
        "user_id": 45,
        "description": "Менеджер по логистике",
        "status": "work",
        "phone": "+380684567890",
        "viber": "+380684567890",
        "telegram": "@artyom_logist",
        "password": "securepass15",
    },
    {
        "first_name": "Светлана",
        "second_name": "Борисовна",
        "last_name": "Ковалева",
        "email": "kovaleva@example.com",
        "date_birthday": "1979-11-29",
        "image": None,
        "user_id": 46,
        "description": "Бухгалтер",
        "status": "work",
        "phone": "+380995678901",
        "viber": "+380995678901",
        "telegram": "@sveta_buh",
        "password": "securepass16",
    },
    {
        "first_name": "Владимир",
        "second_name": "Петрович",
        "last_name": "Ершов",
        "email": "ershov@example.com",
        "date_birthday": "1972-04-22",
        "image": None,
        "user_id": 47,
        "description": "Водитель",
        "status": "work",
        "phone": "+380636789012",
        "viber": "+380636789012",
        "telegram": "@vova_drive",
        "password": "securepass17",
    },
    {
        "first_name": "Наталья",
        "second_name": "Михайловна",
        "last_name": "Филиппова",
        "email": "filippova@example.com",
        "date_birthday": "1996-09-01",
        "image": None,
        "user_id": 48,
        "description": "Ассистент менеджера",
        "status": "work",
        "phone": "+380977890123",
        "viber": "+380977890123",
        "telegram": "@nata_assist",
        "password": "securepass18",
    },
    {
        "first_name": "Роман",
        "second_name": "Валерьевич",
        "last_name": "Зайцев",
        "email": "zaitsev@example.com",
        "date_birthday": "1984-12-12",
        "image": None,
        "user_id": 49,
        "description": "Продавец-консультант",
        "status": "work",
        "phone": "+380508901234",
        "viber": "+380508901234",
        "telegram": "@roma_sale",
        "password": "securepass19",
    },
    {
        "first_name": "Юлия",
        "second_name": "Андреевна",
        "last_name": "Белова",
        "email": "belova@example.com",
        "date_birthday": "1998-05-07",
        "image": None,
        "user_id": 50,
        "description": "Стажер в IT отделе",
        "status": "work",
        "phone": "+380679012345",
        "viber": "+380679012345",
        "telegram": "@yulia_it",
        "password": "securepass20",
    },
]

HOUSES = [
    {
        "title": "ЖК Тихая Пристань",
        "address": "г. Киев, ул. Центральная, 10",
    },
    {
        "title": "ЖК Золотой Берег",
        "address": "г. Киев, ул. Победы, 25",
    },
]
